'use strict';
const $=s=>document.querySelector(s),C=DGCore,money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0)/100),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=d=>d?String(d).slice(0,10).split('-').reverse().join('/'):'—';
let session=null;try{session=JSON.parse(sessionStorage.getItem('gordinho-session')||'null');}catch(e){sessionStorage.removeItem('gordinho-session');}
let data={clients:[],loans:[],payments:[],expenses:[]},view='dashboard',filter='',query='',ready=false;
const uid=()=>crypto.randomUUID(),client=id=>data.clients.find(c=>c.id===id)||{name:'Cliente não encontrado'},sum=(a,key)=>a.reduce((s,x)=>s+Number(x[key]||0),0),calc=l=>C.calculate(l,data.payments),badge=s=>`<span class="badge ${s==='Atrasado'?'late':s==='Encerrado'?'closed':''}">${s}</span>`;
async function api(action,fields={}){
  const payload={action,token:session?.token,...fields};let r;
  const url=window.DG_CONFIG?.API_URL;if(!/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec$/.test(url||''))throw Error('Configure a URL /exec do Google Script no arquivo config.js.');
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);
    try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow',signal:controller.signal});if(!response.ok)throw Error('Servidor indisponível.');r=await response.json();}catch(e){throw Error('Não foi possível conectar. Verifique a implantação do Google Script. Se você estava salvando, atualize antes de repetir.');}finally{clearTimeout(timer);}
  if(!r.ok){if(r.code==='AUTH')signOut(false);throw Error(r.error||'Não foi possível concluir.');}return r.data;
}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4000);}
function modal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal-error').hidden=true;if(!$('#modal').open)$('#modal').showModal();}
function field(label,name,type='text',value='',attrs=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;}
function area(label,name,value=''){return `<label class="full">${label}<textarea name="${name}" maxlength="3000">${esc(value)}</textarea></label>`;}
function select(label,name,items,current=''){return `<label>${label}<select name="${name}" required>${items.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
function actions(label='Salvar'){return `<div class="form-actions"><button type="button" data-cancel>Cancelar</button><button class="primary" type="submit">${label}</button></div>`;}
function bindForm(action,transform=x=>x,after){const form=$('#modal-body form'),requestId=uid();form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;$('#modal-error').hidden=true;try{const p=transform(Object.fromEntries(new FormData(form)));await api(action,{data:p,requestId});$('#modal').close();toast('Registro salvo.');await load();if(after)after();}catch(err){$('#modal-error').textContent=err.message;$('#modal-error').hidden=false;}finally{button.disabled=false;}});}
async function load(){const error=$('#error');error.hidden=true;$('#refresh').disabled=true;try{data=await api('load');ready=true;render();}catch(e){error.textContent=e.message;error.hidden=false;if(!ready)$('#content').innerHTML='<div class="panel empty"><h3>Não foi possível carregar</h3><p>Use Atualizar para tentar novamente.</p></div>';}finally{$('#refresh').disabled=false;}}
function showApp(){ $('#login').hidden=true;$('#app').hidden=false;$('#content').innerHTML='<div class="panel empty">Carregando seus registros…</div>';load();}
async function signOut(remote=true){const old=session;session=null;sessionStorage.removeItem('gordinho-session');data={clients:[],loans:[],payments:[],expenses:[]};ready=false;$('#app').hidden=true;$('#login').hidden=false;$('#modal').close();if(remote&&old){try{await api('logout',{token:old.token});}catch(e){}}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('#login-error').textContent='';try{session=await api('login',Object.fromEntries(new FormData(e.target)));sessionStorage.setItem('gordinho-session',JSON.stringify(session));e.target.password.value='';showApp();}catch(err){$('#login-error').textContent=err.message;}finally{b.disabled=false;}});
$('#logout').onclick=()=>signOut();$('#refresh').onclick=load;$('#close-modal').onclick=()=>$('#modal').close();$('#new-loan').onclick=newLoan;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-cancel'))$('#modal').close();if(b.dataset.view){view=b.dataset.view;query='';filter='';render();}if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.client)clientForm(b.dataset.client);if(b.dataset.pay)payForm(b.dataset.pay);if(b.dataset.reverse)reasonForm('Estornar pagamento','O registro será preservado no histórico e o saldo será recalculado.','reverse',b.dataset.reverse);if(b.dataset.close)reasonForm('Encerrar com baixa','O capital ainda não recuperado será registrado como prejuízo. Os juros não recebidos serão baixados separadamente.','close',b.dataset.close);if(b.dataset.reopen)reopen(b.dataset.reopen);if(b.dataset.notes)notesForm(b.dataset.notes);});
function metrics(items){return `<div class="metrics">${items.map(([name,value,help,color])=>`<div class="metric ${color||''}"><span>${name}</span><strong>${money(value)}</strong><small>${help}</small></div>`).join('')}</div>`;}
function totals(){const summaries=data.loans.map(calc);return {lent:sum(data.loans,'principal'),received:sum(summaries,'paid'),capital:sum(summaries,'principalRecovered'),profit:sum(summaries,'profit'),loss:sum(summaries,'loss'),balance:sum(summaries,'balance'),expected:sum(summaries,'expected'),late:sum(summaries,'overdue'),expenses:sum(data.expenses,'amount')};}
function empty(title,description){return `<div class="empty"><h3>${title}</h3><p>${description}</p></div>`;}
function loanTable(loans){if(!loans.length)return empty('Nenhum empréstimo encontrado','Cadastre um empréstimo ou ajuste os filtros.');return `<div class="table-wrap"><table><thead><tr><th>Cliente / empréstimo</th><th>Emprestado</th><th>Saldo devedor</th><th>Vencimento</th><th>Situação</th><th></th></tr></thead><tbody>${loans.map(l=>{const s=calc(l);return `<tr><td><strong>${esc(client(l.clientId).name)}</strong><small>#${esc(l.id.slice(0,8))} · ${l.rate}% de juros</small></td><td>${money(l.principal)}</td><td><strong>${money(s.balance)}</strong></td><td>${fmt(s.next?.due)}${s.days?`<small class="red">${s.days} dias de atraso</small>`:''}</td><td>${badge(s.status)}</td><td><button data-detail="${esc(l.id)}">Abrir</button></td></tr>`;}).join('')}</tbody></table></div>`;}
function render(){if(!ready)return;const titles={dashboard:'Visão geral',loans:'Empréstimos',clients:'Clientes',payments:'Pagamentos',results:'Resultados'};$('#view-title').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const t=totals(),node=$('#content');
  if(view==='dashboard'){
    const active=data.loans.filter(l=>calc(l).balance>0),due=active.slice().sort((a,b)=>calc(a).next.due.localeCompare(calc(b).next.due)).slice(0,6),states=[['Em dia',active.filter(l=>calc(l).status==='Em dia').length],['Atrasados',active.filter(l=>calc(l).status==='Atrasado').length],['Quitados',data.loans.filter(l=>calc(l).status==='Quitado').length],['Encerrados',data.loans.filter(l=>l.closed).length]];
    node.innerHTML=metrics([['Saldo a receber',t.balance,`${active.length} empréstimos em aberto`,'accent'],['Total recebido',t.received,'Capital + juros recebidos'],['Lucro recebido',t.profit,'Juros efetivamente recebidos','green'],['Parcelas atrasadas',t.late,'Somente valores já vencidos','red']])+`<section class="panel"><div class="panel-head"><h2>Próximos recebimentos</h2><button data-view="loans">Ver todos</button></div>${loanTable(due)}</section><div class="two"><section class="panel"><h2>Situação da carteira</h2><div class="bars">${states.map(([name,n])=>`<div><div class="bar-label"><span>${name}</span><strong>${n}</strong></div><div class="bar"><i style="width:${data.loans.length?Number(n)/data.loans.length*100:0}%"></i></div></div>`).join('')}</div></section><section class="panel"><h2>Resumo financeiro</h2><div class="split"><span>Capital emprestado</span><strong>${money(t.lent)}</strong></div><div class="split"><span>Capital recuperado</span><strong>${money(t.capital)}</strong></div><div class="split"><span>Lucro ainda previsto</span><strong>${money(t.expected)}</strong></div><div class="split"><span>Prejuízo registrado</span><strong class="red">${money(t.loss)}</strong></div><div class="split total"><span>Resultado líquido</span><strong class="${t.profit-t.loss-t.expenses<0?'red':'green'}">${money(t.profit-t.loss-t.expenses)}</strong></div></section></div>`;
  }else if(view==='loans'){
    node.innerHTML=`<section class="panel"><div class="toolbar"><input id="search" placeholder="Buscar cliente ou empréstimo" aria-label="Buscar" value="${esc(query)}"><select id="filter" aria-label="Situação">${['Todas','Em dia','Atrasado','Quitado','Encerrado'].map(v=>`<option ${v===filter?'selected':''}>${v}</option>`).join('')}</select></div><div id="loan-list"></div></section>`;const update=()=>{query=$('#search').value;filter=$('#filter').value;$('#loan-list').innerHTML=loanTable(data.loans.filter(l=>(client(l.clientId).name+' '+l.id).toLowerCase().includes(query.toLowerCase())&&(!filter||filter==='Todas'||calc(l).status===filter)).slice().reverse());};$('#search').oninput=update;$('#filter').onchange=update;update();
  }else if(view==='clients'){
    node.innerHTML=`<section class="panel"><div class="panel-head"><h2>${data.clients.length} clientes cadastrados</h2><button id="add-client" class="primary">+ Novo cliente</button></div><input id="client-search" placeholder="Buscar nome ou telefone" aria-label="Buscar cliente"><div id="client-list"></div></section>`;$('#add-client').onclick=()=>clientForm();const update=()=>{const q=$('#client-search').value.toLowerCase(),clients=data.clients.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q));$('#client-list').innerHTML=clients.length?`<div class="table-wrap"><table><thead><tr><th>Nome</th><th>Telefone</th><th>Empréstimos</th><th>Saldo em aberto</th><th></th></tr></thead><tbody>${clients.map(c=>{const ls=data.loans.filter(l=>l.clientId===c.id);return `<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.phone)||'—'}</td><td>${ls.length}</td><td>${money(ls.reduce((s,l)=>s+calc(l).balance,0))}</td><td><button data-client="${esc(c.id)}">Editar</button></td></tr>`;}).join('')}</tbody></table></div>`:empty('Cadastre seu primeiro cliente','Nome, contato, endereço e observações ficam reunidos aqui.');};$('#client-search').oninput=update;update();
  }else if(view==='payments'){
    node.innerHTML=`<section class="panel"><div class="panel-head"><h2>Histórico de recebimentos</h2><button id="export">Exportar CSV</button></div>${paymentTable(data.payments.slice().reverse(),true)}</section>`;$('#export').onclick=exportCSV;
  }else{
    node.innerHTML=metrics([['Lucro recebido',t.profit,'Após recuperar o capital','green'],['Lucro previsto',t.expected,'Juros pendentes em contratos abertos'],['Prejuízo registrado',t.loss,'Capital baixado e não recuperado','red'],['Resultado líquido',t.profit-t.loss-t.expenses,'Lucro − prejuízo − despesas','accent']])+`<div class="two"><section class="panel"><h2>Composição do resultado</h2><div class="split"><span>Total recebido</span><strong>${money(t.received)}</strong></div><div class="split"><span>Capital recuperado</span><strong>${money(t.capital)}</strong></div><div class="split"><span>Juros recebidos</span><strong>${money(t.profit)}</strong></div><div class="split"><span>Prejuízo em capital</span><strong>${money(t.loss)}</strong></div><div class="split"><span>Despesas</span><strong>${money(t.expenses)}</strong></div><p class="note" style="margin-top:20px">Valores acumulados de toda a carteira. Cada pagamento recupera primeiro o capital; o excedente é lucro. Atraso não é prejuízo automático. Juros não recebidos não entram no resultado.</p></section><section class="panel"><div class="panel-head"><h2>Despesas</h2><button id="add-expense">+ Registrar</button></div>${data.expenses.length?`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th></tr></thead><tbody>${data.expenses.slice().reverse().map(e=>`<tr><td>${fmt(e.date)}</td><td>${esc(e.description)}</td><td>${money(e.amount)}</td></tr>`).join('')}</tbody></table></div>`:empty('Nenhuma despesa registrada','Registre seus custos para acompanhar o resultado líquido.')}</section></div>`;$('#add-expense').onclick=expenseForm;
  }
}
function clientForm(id){const c=data.clients.find(x=>x.id===id)||{};modal(id?'Editar cliente':'Novo cliente',`<form><div class="form-grid">${field('Nome completo','name','text',c.name||'','required maxlength="120"')}${field('Telefone / WhatsApp','phone','tel',c.phone||'','maxlength="30"')}${field('CPF / documento (opcional)','document','text',c.document||'','maxlength="30"')}${field('Endereço','address','text',c.address||'','maxlength="300"')}${area('Observações do cliente','notes',c.notes)}</div>${actions()}</form>`);bindForm('saveClient',p=>({...p,id}));}
function newLoan(){if(!ready){toast('Aguarde carregar os dados.');return;}if(!data.clients.length){clientForm();toast('Cadastre um cliente antes de criar o empréstimo.');return;}
  modal('Novo empréstimo',`<form><div class="form-grid"><div class="full">${select('Cliente','clientId',data.clients.map(c=>[c.id,c.name]))}</div>${field('Valor emprestado (R$)','principal','number','','required min="0.01" max="10000000" step="0.01"')}${field('Juros sobre o contrato (%)','rate','number','10','required min="0" max="1000" step="0.01"')}${field('Data de liberação','start','date',C.today(),'required')}${field('Primeiro vencimento','firstDue','date',C.today(),'required')}${select('Periodicidade das parcelas','period',[['unica','Pagamento único'],['semanal','Semanal'],['quinzenal','Quinzenal'],['mensal','Mensal'],['diaria','Diária']])}${field('Número de parcelas','count','number','1','required min="1" max="120" step="1"')}${area('Observações / condições combinadas','notes')}</div><div id="loan-preview" class="preview"></div><p class="note">A porcentagem incide uma única vez sobre o valor emprestado. As parcelas dividem o total. Não há juros extras automáticos por atraso.</p>${actions('Cadastrar empréstimo')}</form>`);
  const form=$('#modal-body form');const preview=()=>{const p=Object.fromEntries(new FormData(form));if(p.period==='unica')form.elements.count.value='1';try{const principal=C.cents(p.principal),interest=Math.round(principal*Number(p.rate)/100),count=Number(form.elements.count.value);const dates=C.schedule(p.firstDue,count,p.period,principal+interest);$('#loan-preview').innerHTML=`Juros: <b>${money(interest)}</b> · Total a receber: <strong>${money(principal+interest)}</strong><br>${count} parcela(s) · primeira: ${money(dates[0].amount)} · último vencimento: ${fmt(dates.at(-1).due)}`;}catch(e){$('#loan-preview').textContent='Preencha os valores e as datas para simular.';}};form.oninput=preview;form.onchange=preview;preview();bindForm('createLoan');
}
function detail(id){const l=data.loans.find(x=>x.id===id);if(!l)return;const s=calc(l),c=client(l.clientId);modal('Empréstimo #'+l.id.slice(0,8),`<h3>${esc(c.name)} ${badge(s.status)}</h3><p class="muted">${esc(c.phone)} · Liberado em ${fmt(l.start)}</p><div class="detail-stats">${[['Capital',l.principal],['Juros contratados',l.interest],['Total recebido',s.paid],['Saldo devedor',s.balance],['Lucro recebido',s.profit],['Prejuízo',s.loss]].map(([n,v])=>`<div><span>${n}</span><strong>${money(v)}</strong></div>`).join('')}</div><p class="detail-info">${esc(l.notes)||'Sem observações.'}</p>${l.closed?`<div class="error">Baixa em ${fmt(l.closedAt)}: ${esc(l.closeReason)}<br>Saldo baixado: ${money(s.forgiven)}. Capital perdido: ${money(s.loss)}.</div>`:''}<div class="detail-actions">${s.balance>0?`<button class="primary" data-pay="${id}">Registrar pagamento</button>`:''}<button data-notes="${id}">Editar observações</button>${l.closed?`<button data-reopen="${id}">Reabrir empréstimo</button>`:s.balance>0?`<button class="danger" data-close="${id}">Encerrar com baixa</button>`:''}<button id="print">Imprimir resumo</button></div><h3>Parcelas combinadas</h3><div class="table-wrap"><table><thead><tr><th>Parcela</th><th>Vencimento</th><th>Valor</th><th>Recebido</th><th>Saldo</th></tr></thead><tbody>${s.installments.map(p=>`<tr><td>${p.number}</td><td>${fmt(p.due)}</td><td>${money(p.amount)}</td><td>${money(p.paid)}</td><td>${money(p.balance)}${l.closed?' (baixado)':''}</td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:26px">Histórico de pagamentos</h3>${paymentTable(data.payments.filter(p=>p.loanId===id).slice().reverse(),false)}`);$('#print').onclick=()=>window.print();}
function paymentTable(payments,showClient){return payments.length?`<div class="table-wrap"><table><thead><tr><th>Data</th>${showClient?'<th>Cliente</th>':''}<th>Valor</th><th>Forma / observação</th><th></th></tr></thead><tbody>${payments.map(p=>{const l=data.loans.find(l=>l.id===p.loanId);return `<tr><td>${fmt(p.date)}</td>${showClient?`<td>${esc(client(l?.clientId).name)}</td>`:''}<td><strong class="${p.reversed?'red':''}">${money(p.amount)}</strong>${p.reversed?'<small>Estornado</small>':''}</td><td>${esc(p.method)}<small>${esc(p.reversed?p.reverseReason:p.notes)}</small></td><td>${!p.reversed&&!l?.closed?`<button class="danger" data-reverse="${p.id}">Estornar</button>`:''}${showClient?` <button data-detail="${esc(p.loanId)}">Abrir</button>`:''}</td></tr>`;}).join('')}</tbody></table></div>`:empty('Nenhum pagamento','Registre um recebimento dentro do empréstimo.');}
function payForm(id){const l=data.loans.find(l=>l.id===id),s=calc(l);modal('Registrar pagamento',`<p>${esc(client(l.clientId).name)} · Saldo <b>${money(s.balance)}</b></p><form><div class="form-grid">${field('Valor recebido (R$)','amount','number',(s.next?.balance||s.balance)/100,`required min="0.01" max="${s.balance/100}" step="0.01"`)}${field('Data do recebimento','date','date',C.today(),`required min="${l.start}" max="${C.today()}"`)}${select('Forma de pagamento','method',[['PIX','PIX'],['Dinheiro','Dinheiro'],['Transferência','Transferência'],['Outro','Outro']])}${area('Observação do pagamento','notes')}</div><p class="note">Pagamentos parciais são aceitos. O saldo abate as parcelas mais antigas primeiro.</p>${actions('Confirmar recebimento')}</form>`);bindForm('pay',p=>({...p,loanId:id}),()=>detail(id));}
function reasonForm(title,help,action,id){modal(title,`<p class="note">${help}</p><form>${area('Motivo (obrigatório)','reason')}${actions('Confirmar')}</form>`);$('#modal-body textarea').required=true;bindForm(action,p=>({...p,id}),()=>{const loan=action==='reverse'?data.payments.find(p=>p.id===id)?.loanId:id;detail(loan);});}
function notesForm(id){modal('Observações do empréstimo',`<form>${area('Condições / observações','notes',data.loans.find(l=>l.id===id).notes)}${actions()}</form>`);bindForm('notes',p=>({...p,id}),()=>detail(id));}
async function reopen(id){modal('Reabrir empréstimo',`<p>O saldo voltará para a carteira e o prejuízo dessa baixa será removido.</p><form>${actions('Confirmar reabertura')}</form>`);bindForm('reopen',p=>({...p,id}),()=>detail(id));}
function expenseForm(){modal('Registrar despesa',`<form><div class="form-grid">${field('Valor (R$)','amount','number','','required min="0.01" step="0.01"')}${field('Data','date','date',C.today(),`required max="${C.today()}"`)}<div class="full">${field('Descrição','description','text','','required maxlength="500"')}</div></div>${actions()}</form>`);bindForm('expense');}
$('#password-btn').onclick=()=>{modal('Alterar senha',`<form>${field('Senha atual','current','password','','required autocomplete="current-password"')}${field('Nova senha (mínimo 12 caracteres)','password','password','','required minlength="12" maxlength="200" autocomplete="new-password"')}${field('Confirmar nova senha','confirm','password','','required autocomplete="new-password"')}${actions('Alterar senha')}</form>`);const form=$('#modal-body form');form.onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(form)),b=form.querySelector('[type=submit]');b.disabled=true;try{if(p.password!==p.confirm)throw Error('As senhas não conferem.');await api('changePassword',p);signOut(false);toast('Senha alterada. Entre novamente.');}catch(e){$('#modal-error').textContent=e.message;$('#modal-error').hidden=false;}finally{b.disabled=false;}};};
function exportCSV(){const protect=v=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const rows=[['Data','Cliente','Empréstimo','Valor R$','Forma','Observação','Estornado','Motivo'],...data.payments.map(p=>{const l=data.loans.find(l=>l.id===p.loanId);return [p.date,client(l?.clientId).name,p.loanId,(p.amount/100).toFixed(2).replace('.',','),p.method,p.notes,p.reversed?'Sim':'Não',p.reverseReason];})];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(protect).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='pagamentos-'+C.today()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if(session&&session.expires>Date.now())showApp();else signOut(false);
